import type { Metadata } from 'next'
import { Inter , Poppins , Whisper} from 'next/font/google'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'] , weight:['400'] , variable: '--font-inter'})
const whisper = Whisper({ variable: '--font-whisper' ,subsets: ['latin'] , weight:['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${poppins.variable} ${whisper.variable}`}>{children}</body>
    </html>
  )
}
